import { computeReviewStats } from '../data/stats.js';

const CONFIDENCE_LEVELS = new Set(['high', 'medium', 'low']);

function excerptFor(review, limit = 180) {
  const text = (review.content || review.title || '').slice(0, limit);
  return `${review.review_id}: ${text}`;
}

function deterministicEvidenceStrength(finding, classified, minSupport) {
  const members = classified.filter((r) => finding.review_ids.includes(r.review_id));
  const supportCount = finding.review_ids.length;
  const conflicts = (finding.conflicting_review_ids ?? []).filter((id) =>
    classified.some((r) => r.review_id === id),
  );
  const conflictShare = supportCount + conflicts.length ? conflicts.length / (supportCount + conflicts.length) : 0;
  const ratings = members.map((r) => r.rating);
  const avgRating = ratings.length ? ratings.reduce((a, b) => a + b, 0) / ratings.length : 0;
  const negativeShare = ratings.length ? ratings.filter((r) => r <= 2).length / ratings.length : 0;
  const positiveShare = ratings.length ? ratings.filter((r) => r >= 4).length / ratings.length : 0;
  const consistency = Math.max(negativeShare, positiveShare, 1 - Math.abs(negativeShare - positiveShare));
  const score = supportCount * (0.6 + consistency * 0.4) - conflictShare * supportCount * 0.5;
  const evidenceStatus = supportCount >= minSupport ? 'supported' : 'insufficient_evidence';
  const confidence =
    score >= 12 ? 'high' : score >= 5 ? 'medium' : 'low';
  return {
    support_count: supportCount,
    conflict_count: conflicts.length,
    conflict_share: Number(conflictShare.toFixed(3)),
    average_rating: Number(avgRating.toFixed(2)),
    negative_share: Number(negativeShare.toFixed(3)),
    positive_share: Number(positiveShare.toFixed(3)),
    consistency: Number(consistency.toFixed(3)),
    evidence_score: Number(score.toFixed(2)),
    evidence_status: evidenceStatus,
    confidence,
  };
}

export function validateFindings(findings, { reviewIds, topicIds, minSupport, classified }) {
  const issues = [];
  const ids = new Set();
  const sanitized = [];
  for (const finding of findings ?? []) {
    const f = { ...finding };
    if (!f.finding_id || ids.has(f.finding_id)) {
      issues.push(`Invalid or duplicate finding id: ${f.finding_id}`);
      continue;
    }
    ids.add(f.finding_id);
    if (f.topic_id && !topicIds.has(f.topic_id)) {
      issues.push(`${f.finding_id} references unknown topic ${f.topic_id}.`);
      f.topic_id = null;
    }
    const validIds = [...new Set((f.review_ids ?? []).filter((id) => reviewIds.has(id)))];
    if (validIds.length !== (f.review_ids ?? []).length) {
      issues.push(`${f.finding_id} referenced review IDs that do not exist; dropped them.`);
      f.review_ids = validIds;
    }
    f.conflicting_review_ids = (f.conflicting_review_ids ?? []).filter((id) => reviewIds.has(id));
    if (!Array.isArray(f.excerpts)) f.excerpts = [];
    if (!CONFIDENCE_LEVELS.has(f.confidence)) f.confidence = 'low';
    if (!f.model_conclusion) f.model_conclusion = false;
    const evidence = deterministicEvidenceStrength(f, classified ?? [], minSupport);
    f.support_count = evidence.support_count;
    f.deterministic_evidence = evidence;
    f.model_confidence = f.confidence;
    f.confidence = evidence.confidence;
    f.evidence_status = evidence.evidence_status;
    f.status = evidence.evidence_status === 'supported' ? 'supported' : 'assumption';
    if (evidence.support_count === 0) {
      issues.push(`${f.finding_id} has no valid supporting reviews; removed.`);
      continue;
    }
    sanitized.push(f);
  }
  return { findings: sanitized, issues };
}

function fallbackFindings(topics, classification, minSupport) {
  return topics
    .map((topic, index) => {
      const members = classification.classified.filter((r) => r.topics.includes(topic.id));
      if (members.length === 0) return null;
      const stats = computeReviewStats(members);
      const reviewIds = members.slice(0, 30).map((r) => r.review_id);
      const finding = {
        finding_id: `F-${String(index + 1).padStart(2, '0')}`,
        title: `${topic.name}: rule-based fallback finding`,
        summary: `Reviews assigned to "${topic.name}" by the rule-based fallback.`,
        topic_id: topic.id,
        review_ids: reviewIds,
        excerpts: members.slice(0, 3).map(excerptFor),
        support_count: reviewIds.length,
        confidence: 'low',
        conflicting_review_ids: [],
        statistical_basis: {
          average_rating: stats.average_rating,
          negative_share: stats.negative_share,
          positive_share: stats.positive_share,
        },
        model_conclusion: false,
        assumptions: ['Generated by rule-based fallback because the model was unavailable.'],
        fallback: true,
      };
      const evidence = deterministicEvidenceStrength(finding, classification.classified, minSupport);
      return {
        ...finding,
        deterministic_evidence: evidence,
        evidence_status: evidence.evidence_status,
        status: evidence.evidence_status === 'supported' ? 'supported' : 'assumption',
        model_confidence: 'low',
        confidence: evidence.confidence,
      };
    })
    .filter(Boolean);
}

export async function runFindingGeneration({ scoped, topics, classification, llm, onEvent, minSupport }) {
  const reviewIds = new Set(classification.classified.map((r) => r.review_id));
  const topicIds = new Set(topics.map((t) => t.id));
  let findings = [];
  let method = 'model';
  let error = null;
  const validationIssues = [];

  if (llm && llm.available()) {
    try {
      const result = await llm.completeJSON('finding_generation', {
        goal: scoped.scope?.summary ?? '',
        focus_areas: scoped.scope?.focus_areas ?? [],
        app: scoped.scope?.app ?? null,
        dataset_stats: scoped.stats,
        topics: topics.map((t) => ({
          id: t.id,
          name: t.name,
          description: t.description,
          rating_bias: t.rating_bias,
          member_count: classification.topic_stats.find((s) => s.topic_id === t.id)?.member_count ?? 0,
        })),
        topic_stats: classification.topic_stats,
        classified_reviews: classification.classified.map((r) => ({
          review_id: r.review_id,
          rating: r.rating,
          version: r.version,
          language: r.language,
          title: r.title,
          content: r.content.slice(0, 180),
          sentiment: r.sentiment,
          topics: r.topics,
          votes: r.vote_count,
        })),
      }, 'findings');
      const validated = validateFindings(result.findings, { reviewIds, topicIds, minSupport, classified: classification.classified });
      validationIssues.push(...validated.issues);
      findings = validated.findings;
      if (findings.length === 0) {
        method = 'fallback';
        error = 'Model findings were all rejected by validation.';
      }
    } catch (err) {
      method = 'fallback';
      error = err.message;
      onEvent?.({ type: 'finding_generation_failed', error: err.message });
    }
  } else {
    method = 'fallback';
    error = 'LLM provider unavailable.';
  }

  if (findings.length === 0) {
    findings = fallbackFindings(topics, classification, minSupport);
  }

  return {
    findings,
    method,
    degraded: method === 'fallback',
    error,
    validation_issues: validationIssues,
  };
}

